### ISSUE TITLE
perch_member_form versus perch_members_form

### ISSUE THREAD

**Issue by mandashafer** [Pipits/pipit-members#4]
On this page: https://grabapipit.com/pipits/apps/members/docs/forms/collection-item

Under "Creating a new item"

Should the documentation say "perch_member_form()" Singular
OR
"pipits_members_form()"  with pipits.

**Comment by husseinalhammad** [comment]
That's a typo. It is meant to be [perch_member_form()](https://docs.grabaperch.com/functions/members/perch-member-form/).

Thanks for flagging this. I'll keep this issue open until I fix the docs.

**Comment by husseinalhammad** [comment]
Docs have been updated. Thanks again, @mandashafer.
